# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/zyhfunny/Documents/VSC_PROJ/FileArchiver

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/zyhfunny/Documents/VSC_PROJ/FileArchiver

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/opt/homebrew/bin/ctest $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/zyhfunny/Documents/VSC_PROJ/FileArchiver/CMakeFiles /Users/zyhfunny/Documents/VSC_PROJ/FileArchiver//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/zyhfunny/Documents/VSC_PROJ/FileArchiver/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /Users/zyhfunny/Documents/VSC_PROJ/FileArchiver/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named filearchiver_core

# Build rule for target.
filearchiver_core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 filearchiver_core
.PHONY : filearchiver_core

# fast build rule for target.
filearchiver_core/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/filearchiver_core.dir/build.make CMakeFiles/filearchiver_core.dir/build
.PHONY : filearchiver_core/fast

#=============================================================================
# Target rules for targets named filearchiver

# Build rule for target.
filearchiver: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 filearchiver
.PHONY : filearchiver

# fast build rule for target.
filearchiver/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/filearchiver.dir/build.make CMakeFiles/filearchiver.dir/build
.PHONY : filearchiver/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) $(MAKESILENT) -f libs/yaml-cpp/CMakeFiles/Experimental.dir/build.make libs/yaml-cpp/CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) $(MAKESILENT) -f libs/yaml-cpp/CMakeFiles/Nightly.dir/build.make libs/yaml-cpp/CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) $(MAKESILENT) -f libs/yaml-cpp/CMakeFiles/Continuous.dir/build.make libs/yaml-cpp/CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) $(MAKESILENT) -f libs/yaml-cpp/CMakeFiles/NightlyMemoryCheck.dir/build.make libs/yaml-cpp/CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) $(MAKESILENT) -f libs/yaml-cpp/CMakeFiles/NightlyStart.dir/build.make libs/yaml-cpp/CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) $(MAKESILENT) -f libs/yaml-cpp/CMakeFiles/NightlyUpdate.dir/build.make libs/yaml-cpp/CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) $(MAKESILENT) -f libs/yaml-cpp/CMakeFiles/NightlyConfigure.dir/build.make libs/yaml-cpp/CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) $(MAKESILENT) -f libs/yaml-cpp/CMakeFiles/NightlyBuild.dir/build.make libs/yaml-cpp/CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) $(MAKESILENT) -f libs/yaml-cpp/CMakeFiles/NightlyTest.dir/build.make libs/yaml-cpp/CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) $(MAKESILENT) -f libs/yaml-cpp/CMakeFiles/NightlyCoverage.dir/build.make libs/yaml-cpp/CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f libs/yaml-cpp/CMakeFiles/NightlyMemCheck.dir/build.make libs/yaml-cpp/CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) $(MAKESILENT) -f libs/yaml-cpp/CMakeFiles/NightlySubmit.dir/build.make libs/yaml-cpp/CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) $(MAKESILENT) -f libs/yaml-cpp/CMakeFiles/ExperimentalStart.dir/build.make libs/yaml-cpp/CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) $(MAKESILENT) -f libs/yaml-cpp/CMakeFiles/ExperimentalUpdate.dir/build.make libs/yaml-cpp/CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) $(MAKESILENT) -f libs/yaml-cpp/CMakeFiles/ExperimentalConfigure.dir/build.make libs/yaml-cpp/CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) $(MAKESILENT) -f libs/yaml-cpp/CMakeFiles/ExperimentalBuild.dir/build.make libs/yaml-cpp/CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) $(MAKESILENT) -f libs/yaml-cpp/CMakeFiles/ExperimentalTest.dir/build.make libs/yaml-cpp/CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) $(MAKESILENT) -f libs/yaml-cpp/CMakeFiles/ExperimentalCoverage.dir/build.make libs/yaml-cpp/CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f libs/yaml-cpp/CMakeFiles/ExperimentalMemCheck.dir/build.make libs/yaml-cpp/CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) $(MAKESILENT) -f libs/yaml-cpp/CMakeFiles/ExperimentalSubmit.dir/build.make libs/yaml-cpp/CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) $(MAKESILENT) -f libs/yaml-cpp/CMakeFiles/ContinuousStart.dir/build.make libs/yaml-cpp/CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) $(MAKESILENT) -f libs/yaml-cpp/CMakeFiles/ContinuousUpdate.dir/build.make libs/yaml-cpp/CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) $(MAKESILENT) -f libs/yaml-cpp/CMakeFiles/ContinuousConfigure.dir/build.make libs/yaml-cpp/CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) $(MAKESILENT) -f libs/yaml-cpp/CMakeFiles/ContinuousBuild.dir/build.make libs/yaml-cpp/CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) $(MAKESILENT) -f libs/yaml-cpp/CMakeFiles/ContinuousTest.dir/build.make libs/yaml-cpp/CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) $(MAKESILENT) -f libs/yaml-cpp/CMakeFiles/ContinuousCoverage.dir/build.make libs/yaml-cpp/CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f libs/yaml-cpp/CMakeFiles/ContinuousMemCheck.dir/build.make libs/yaml-cpp/CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) $(MAKESILENT) -f libs/yaml-cpp/CMakeFiles/ContinuousSubmit.dir/build.make libs/yaml-cpp/CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named yaml-cpp

# Build rule for target.
yaml-cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 yaml-cpp
.PHONY : yaml-cpp

# fast build rule for target.
yaml-cpp/fast:
	$(MAKE) $(MAKESILENT) -f libs/yaml-cpp/CMakeFiles/yaml-cpp.dir/build.make libs/yaml-cpp/CMakeFiles/yaml-cpp.dir/build
.PHONY : yaml-cpp/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f libs/yaml-cpp/CMakeFiles/uninstall.dir/build.make libs/yaml-cpp/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named yaml-cpp-sandbox

# Build rule for target.
yaml-cpp-sandbox: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 yaml-cpp-sandbox
.PHONY : yaml-cpp-sandbox

# fast build rule for target.
yaml-cpp-sandbox/fast:
	$(MAKE) $(MAKESILENT) -f libs/yaml-cpp/util/CMakeFiles/yaml-cpp-sandbox.dir/build.make libs/yaml-cpp/util/CMakeFiles/yaml-cpp-sandbox.dir/build
.PHONY : yaml-cpp-sandbox/fast

#=============================================================================
# Target rules for targets named yaml-cpp-parse

# Build rule for target.
yaml-cpp-parse: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 yaml-cpp-parse
.PHONY : yaml-cpp-parse

# fast build rule for target.
yaml-cpp-parse/fast:
	$(MAKE) $(MAKESILENT) -f libs/yaml-cpp/util/CMakeFiles/yaml-cpp-parse.dir/build.make libs/yaml-cpp/util/CMakeFiles/yaml-cpp-parse.dir/build
.PHONY : yaml-cpp-parse/fast

#=============================================================================
# Target rules for targets named yaml-cpp-read

# Build rule for target.
yaml-cpp-read: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 yaml-cpp-read
.PHONY : yaml-cpp-read

# fast build rule for target.
yaml-cpp-read/fast:
	$(MAKE) $(MAKESILENT) -f libs/yaml-cpp/util/CMakeFiles/yaml-cpp-read.dir/build.make libs/yaml-cpp/util/CMakeFiles/yaml-cpp-read.dir/build
.PHONY : yaml-cpp-read/fast

src/archive/archive.o: src/archive/archive.cpp.o
.PHONY : src/archive/archive.o

# target to build an object file
src/archive/archive.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/filearchiver_core.dir/build.make CMakeFiles/filearchiver_core.dir/src/archive/archive.cpp.o
.PHONY : src/archive/archive.cpp.o

src/archive/archive.i: src/archive/archive.cpp.i
.PHONY : src/archive/archive.i

# target to preprocess a source file
src/archive/archive.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/filearchiver_core.dir/build.make CMakeFiles/filearchiver_core.dir/src/archive/archive.cpp.i
.PHONY : src/archive/archive.cpp.i

src/archive/archive.s: src/archive/archive.cpp.s
.PHONY : src/archive/archive.s

# target to generate assembly for a file
src/archive/archive.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/filearchiver_core.dir/build.make CMakeFiles/filearchiver_core.dir/src/archive/archive.cpp.s
.PHONY : src/archive/archive.cpp.s

src/archive/scanner.o: src/archive/scanner.cpp.o
.PHONY : src/archive/scanner.o

# target to build an object file
src/archive/scanner.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/filearchiver_core.dir/build.make CMakeFiles/filearchiver_core.dir/src/archive/scanner.cpp.o
.PHONY : src/archive/scanner.cpp.o

src/archive/scanner.i: src/archive/scanner.cpp.i
.PHONY : src/archive/scanner.i

# target to preprocess a source file
src/archive/scanner.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/filearchiver_core.dir/build.make CMakeFiles/filearchiver_core.dir/src/archive/scanner.cpp.i
.PHONY : src/archive/scanner.cpp.i

src/archive/scanner.s: src/archive/scanner.cpp.s
.PHONY : src/archive/scanner.s

# target to generate assembly for a file
src/archive/scanner.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/filearchiver_core.dir/build.make CMakeFiles/filearchiver_core.dir/src/archive/scanner.cpp.s
.PHONY : src/archive/scanner.cpp.s

src/data/file.o: src/data/file.cpp.o
.PHONY : src/data/file.o

# target to build an object file
src/data/file.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/filearchiver_core.dir/build.make CMakeFiles/filearchiver_core.dir/src/data/file.cpp.o
.PHONY : src/data/file.cpp.o

src/data/file.i: src/data/file.cpp.i
.PHONY : src/data/file.i

# target to preprocess a source file
src/data/file.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/filearchiver_core.dir/build.make CMakeFiles/filearchiver_core.dir/src/data/file.cpp.i
.PHONY : src/data/file.cpp.i

src/data/file.s: src/data/file.cpp.s
.PHONY : src/data/file.s

# target to generate assembly for a file
src/data/file.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/filearchiver_core.dir/build.make CMakeFiles/filearchiver_core.dir/src/data/file.cpp.s
.PHONY : src/data/file.cpp.s

src/data/registry_builtin.o: src/data/registry_builtin.cpp.o
.PHONY : src/data/registry_builtin.o

# target to build an object file
src/data/registry_builtin.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/filearchiver_core.dir/build.make CMakeFiles/filearchiver_core.dir/src/data/registry_builtin.cpp.o
.PHONY : src/data/registry_builtin.cpp.o

src/data/registry_builtin.i: src/data/registry_builtin.cpp.i
.PHONY : src/data/registry_builtin.i

# target to preprocess a source file
src/data/registry_builtin.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/filearchiver_core.dir/build.make CMakeFiles/filearchiver_core.dir/src/data/registry_builtin.cpp.i
.PHONY : src/data/registry_builtin.cpp.i

src/data/registry_builtin.s: src/data/registry_builtin.cpp.s
.PHONY : src/data/registry_builtin.s

# target to generate assembly for a file
src/data/registry_builtin.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/filearchiver_core.dir/build.make CMakeFiles/filearchiver_core.dir/src/data/registry_builtin.cpp.s
.PHONY : src/data/registry_builtin.cpp.s

src/data/repo.o: src/data/repo.cpp.o
.PHONY : src/data/repo.o

# target to build an object file
src/data/repo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/filearchiver_core.dir/build.make CMakeFiles/filearchiver_core.dir/src/data/repo.cpp.o
.PHONY : src/data/repo.cpp.o

src/data/repo.i: src/data/repo.cpp.i
.PHONY : src/data/repo.i

# target to preprocess a source file
src/data/repo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/filearchiver_core.dir/build.make CMakeFiles/filearchiver_core.dir/src/data/repo.cpp.i
.PHONY : src/data/repo.cpp.i

src/data/repo.s: src/data/repo.cpp.s
.PHONY : src/data/repo.s

# target to generate assembly for a file
src/data/repo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/filearchiver_core.dir/build.make CMakeFiles/filearchiver_core.dir/src/data/repo.cpp.s
.PHONY : src/data/repo.cpp.s

src/listener/call_back.o: src/listener/call_back.cpp.o
.PHONY : src/listener/call_back.o

# target to build an object file
src/listener/call_back.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/filearchiver_core.dir/build.make CMakeFiles/filearchiver_core.dir/src/listener/call_back.cpp.o
.PHONY : src/listener/call_back.cpp.o

src/listener/call_back.i: src/listener/call_back.cpp.i
.PHONY : src/listener/call_back.i

# target to preprocess a source file
src/listener/call_back.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/filearchiver_core.dir/build.make CMakeFiles/filearchiver_core.dir/src/listener/call_back.cpp.i
.PHONY : src/listener/call_back.cpp.i

src/listener/call_back.s: src/listener/call_back.cpp.s
.PHONY : src/listener/call_back.s

# target to generate assembly for a file
src/listener/call_back.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/filearchiver_core.dir/build.make CMakeFiles/filearchiver_core.dir/src/listener/call_back.cpp.s
.PHONY : src/listener/call_back.cpp.s

src/listener/macosx.o: src/listener/macosx.cpp.o
.PHONY : src/listener/macosx.o

# target to build an object file
src/listener/macosx.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/filearchiver_core.dir/build.make CMakeFiles/filearchiver_core.dir/src/listener/macosx.cpp.o
.PHONY : src/listener/macosx.cpp.o

src/listener/macosx.i: src/listener/macosx.cpp.i
.PHONY : src/listener/macosx.i

# target to preprocess a source file
src/listener/macosx.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/filearchiver_core.dir/build.make CMakeFiles/filearchiver_core.dir/src/listener/macosx.cpp.i
.PHONY : src/listener/macosx.cpp.i

src/listener/macosx.s: src/listener/macosx.cpp.s
.PHONY : src/listener/macosx.s

# target to generate assembly for a file
src/listener/macosx.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/filearchiver_core.dir/build.make CMakeFiles/filearchiver_core.dir/src/listener/macosx.cpp.s
.PHONY : src/listener/macosx.cpp.s

src/logger.o: src/logger.cpp.o
.PHONY : src/logger.o

# target to build an object file
src/logger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/filearchiver_core.dir/build.make CMakeFiles/filearchiver_core.dir/src/logger.cpp.o
.PHONY : src/logger.cpp.o

src/logger.i: src/logger.cpp.i
.PHONY : src/logger.i

# target to preprocess a source file
src/logger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/filearchiver_core.dir/build.make CMakeFiles/filearchiver_core.dir/src/logger.cpp.i
.PHONY : src/logger.cpp.i

src/logger.s: src/logger.cpp.s
.PHONY : src/logger.s

# target to generate assembly for a file
src/logger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/filearchiver_core.dir/build.make CMakeFiles/filearchiver_core.dir/src/logger.cpp.s
.PHONY : src/logger.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/filearchiver.dir/build.make CMakeFiles/filearchiver.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/filearchiver.dir/build.make CMakeFiles/filearchiver.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/filearchiver.dir/build.make CMakeFiles/filearchiver.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/mathf.o: src/mathf.cpp.o
.PHONY : src/mathf.o

# target to build an object file
src/mathf.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/filearchiver_core.dir/build.make CMakeFiles/filearchiver_core.dir/src/mathf.cpp.o
.PHONY : src/mathf.cpp.o

src/mathf.i: src/mathf.cpp.i
.PHONY : src/mathf.i

# target to preprocess a source file
src/mathf.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/filearchiver_core.dir/build.make CMakeFiles/filearchiver_core.dir/src/mathf.cpp.i
.PHONY : src/mathf.cpp.i

src/mathf.s: src/mathf.cpp.s
.PHONY : src/mathf.s

# target to generate assembly for a file
src/mathf.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/filearchiver_core.dir/build.make CMakeFiles/filearchiver_core.dir/src/mathf.cpp.s
.PHONY : src/mathf.cpp.s

src/renamer.o: src/renamer.cpp.o
.PHONY : src/renamer.o

# target to build an object file
src/renamer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/filearchiver_core.dir/build.make CMakeFiles/filearchiver_core.dir/src/renamer.cpp.o
.PHONY : src/renamer.cpp.o

src/renamer.i: src/renamer.cpp.i
.PHONY : src/renamer.i

# target to preprocess a source file
src/renamer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/filearchiver_core.dir/build.make CMakeFiles/filearchiver_core.dir/src/renamer.cpp.i
.PHONY : src/renamer.cpp.i

src/renamer.s: src/renamer.cpp.s
.PHONY : src/renamer.s

# target to generate assembly for a file
src/renamer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/filearchiver_core.dir/build.make CMakeFiles/filearchiver_core.dir/src/renamer.cpp.s
.PHONY : src/renamer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... Continuous"
	@echo "... ContinuousBuild"
	@echo "... ContinuousConfigure"
	@echo "... ContinuousCoverage"
	@echo "... ContinuousMemCheck"
	@echo "... ContinuousStart"
	@echo "... ContinuousSubmit"
	@echo "... ContinuousTest"
	@echo "... ContinuousUpdate"
	@echo "... Experimental"
	@echo "... ExperimentalBuild"
	@echo "... ExperimentalConfigure"
	@echo "... ExperimentalCoverage"
	@echo "... ExperimentalMemCheck"
	@echo "... ExperimentalStart"
	@echo "... ExperimentalSubmit"
	@echo "... ExperimentalTest"
	@echo "... ExperimentalUpdate"
	@echo "... Nightly"
	@echo "... NightlyBuild"
	@echo "... NightlyConfigure"
	@echo "... NightlyCoverage"
	@echo "... NightlyMemCheck"
	@echo "... NightlyMemoryCheck"
	@echo "... NightlyStart"
	@echo "... NightlySubmit"
	@echo "... NightlyTest"
	@echo "... NightlyUpdate"
	@echo "... uninstall"
	@echo "... filearchiver"
	@echo "... filearchiver_core"
	@echo "... yaml-cpp"
	@echo "... yaml-cpp-parse"
	@echo "... yaml-cpp-read"
	@echo "... yaml-cpp-sandbox"
	@echo "... src/archive/archive.o"
	@echo "... src/archive/archive.i"
	@echo "... src/archive/archive.s"
	@echo "... src/archive/scanner.o"
	@echo "... src/archive/scanner.i"
	@echo "... src/archive/scanner.s"
	@echo "... src/data/file.o"
	@echo "... src/data/file.i"
	@echo "... src/data/file.s"
	@echo "... src/data/registry_builtin.o"
	@echo "... src/data/registry_builtin.i"
	@echo "... src/data/registry_builtin.s"
	@echo "... src/data/repo.o"
	@echo "... src/data/repo.i"
	@echo "... src/data/repo.s"
	@echo "... src/listener/call_back.o"
	@echo "... src/listener/call_back.i"
	@echo "... src/listener/call_back.s"
	@echo "... src/listener/macosx.o"
	@echo "... src/listener/macosx.i"
	@echo "... src/listener/macosx.s"
	@echo "... src/logger.o"
	@echo "... src/logger.i"
	@echo "... src/logger.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/mathf.o"
	@echo "... src/mathf.i"
	@echo "... src/mathf.s"
	@echo "... src/renamer.o"
	@echo "... src/renamer.i"
	@echo "... src/renamer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /Users/zyhfunny/Documents/VSC_PROJ/FileArchiver/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

